### ISSUE TITLE
Wrong spelling 'exipres' causing default expiry to be set everytime

### ISSUE THREAD

**Issue by saurabh-deep** [jsumners/self-cert#1]
https://github.com/jsumners/self-cert/blob/8ce39ce796b89b3e2303df0752331fc6f4fda20e/index.js#L12

In above code 'exipres' needs to be changed to 'expires'. Because of the above, it doesn't matter what expiry date I pass in. It always uses the default one. This certainly needs a fix.

**Comment by jsumners** [comment]
Thank you for the report. I am quite busy. Would you be able to submit a PR?

**Comment by saurabh-deep** [comment]
Just created the [PR](https://github.com/jsumners/self-cert/pull/2).
